version: "{build}"

clone_folder: c:\gopath\src\github.com\turt2live\matrix-media-repo

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.14

init:
  - git config --global core.autocrlf input

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set PATH=c:\go\bin;c:\gopath\bin;%PATH%
  - go version
  - go env

build_script:
  - set GOBIN=%CD%/bin
  - set GO111MODULE=on
  - ps: .\build.ps1

artifacts:
  - path: bin/media_repo.exe
    name: media_repo.exe
  - path: bin/import_synapse.exe
    name: import_synapse.exe
  - path: bin/gdpr_export.exe
    name: gdpr_export.exe
  - path: bin/gdpr_import.exe
    name: gdpr_import.exe

test_script: [] # https://github.com/turt2live/matrix-media-repo/issues/40
