version: "{build}"

# Source Config

clone_folder: c:\gopath\src\github.com\turt2live\matrix-media-repo

# Build host

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.9

init:
  - git config --global core.autocrlf input

# Build

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set Path=c:\go\bin;c:\gopath\bin
  - go version
  - go env
  - go get github.com/constabulary/gb/...
  - gb vendor restore

build_script:
  - gb build all

artifacts:
  - path: bin/media_repo.exe
  - path: bin/import_synapse.exe
