# The configuration for the homeservers this media repository is known to control. Servers
# not listed here will not be able to upload media.
# NOT YET IMPLEMENTED
homeservers:
  - name: t2bot.io
    downloadRequiresAuth: false
    csApi: "https://t2bot.io/"
  - name: t2l.io
    downloadRequiresAuth: false
    csApi: "https://t2l.io/"

# The database configuration for the media repository
database:
  # Currently only "postgres" is supported.
  postgres: "postgres://your_username:your_password@localhost/database_name?sslmode=disable"

# The file upload settings for the media repository
uploads:
  maxBytes: 10485760 # 10MB default, 0 to disable
  # This is intended for larger deployments where media should be distributed among other
  # directories, drives, servers, etc. For smaller deployments, a single entry in this list
  # is recommended.
  storagePaths:
  - /var/matrix/media

# The file download settings when retrieving media from other servers
downloads:
  maxBytes: 10485760 # 10MB default, 0 to disable

# The thumbnail configuration for the media repository.
thumbnails:
  # The maximum number of bytes an image can be before the thumbnailer refuses.
  maxSourceBytes: 10485760 # 10MB default, 0 to disable

  # All thumbnails are generated into one of the sizes listed here. The first size is used as
  # the default for when no width or height is requested. The media repository will return
  # either an exact match or the next largest size of thumbnail.
  sizes:
  - width: 32
    height: 32
  - width: 96
    height: 96
  - width: 320
    height: 240
  - width: 640
    height: 480
  - width: 800
    height: 600