# The configuration for the homeservers this media repository is known to control. Servers
# not listed here will not be able to upload media.
# NOT YET IMPLEMENTED
homeservers:
  - name: t2bot.io
    downloadRequiresAuth: false
    csApi: "https://t2bot.io/"
  - name: t2l.io
    downloadRequiresAuth: false
    csApi: "https://t2l.io/"

# The database configuration for the media repository
database:
  # Currently only "postgres" is supported.
  postgres: "postgres://your_username:your_password@localhost/database_name?sslmode=disable"

uploads:
  maxBytes: 10485760 # 10MB default, 0 to disable
  # This is intended for larger deployments where media should be distributed among other
  # directories, drives, servers, etc. For smaller deployments, a single entry in this list
  # is recommended.
  storagePaths:
  - /var/matrix/media

# NOT YET IMPLEMENTED
thumbails:
  dynamic: false
  sizes:
  - width: 32
    height: 32
    method: crop
  - width: 96
    height: 96
    method: crop
  - width: 320
    height: 240
    method: scale
  - width: 640
    height: 480
    method: scale
  - width: 800
    height: 600
    method: scale