# General repo configuration
repo:
  bindAddress: '127.0.0.1'
  port: 8000
  logDirectory: logs

# The configuration for the homeservers this media repository is known to control. Servers
# not listed here will not be able to upload media.
homeservers:
  - name: t2bot.io
    downloadRequiresAuth: false
    csApi: "https://t2bot.io/"
  - name: t2l.io
    downloadRequiresAuth: false
    csApi: "https://t2l.io/"

# The database configuration for the media repository
database:
  # Currently only "postgres" is supported.
  postgres: "postgres://your_username:your_password@localhost/database_name?sslmode=disable"

# The file upload settings for the media repository
uploads:
  maxBytes: 104857600 # 100MB default, 0 to disable
  # This is intended for larger deployments where media should be distributed among other
  # directories, drives, servers, etc. For smaller deployments, a single entry in this list
  # is recommended.
  storagePaths:
  - /var/matrix/media

# The file download settings when retrieving media from other servers
downloads:
  maxBytes: 104857600 # 100MB default, 0 to disable

# URL Preview settings
urlPreviews:
  enabled: true # If enabled, the preview_url routes will be accessible
  maxPageSizeBytes: 10485760 # 10MB default, 0 to disable

  # Either allowedNetworks or disallowedNetworks must be provided. If both are provided, they
  # will be merged. URL previews will be disabled if neither is supplied. Each entry must be
  # a CIDR range.
  disallowedNetworks:
    - "127.0.0.1/8"
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
    - "100.64.0.0/10"
    - "169.254.0.0/16"
  allowedNetworks:
    - "0.0.0.0/0" # "Everything". The blacklist will help limit this.
                  # This is the default value for this field.

# The thumbnail configuration for the media repository.
thumbnails:
  # The maximum number of bytes an image can be before the thumbnailer refuses.
  maxSourceBytes: 10485760 # 10MB default, 0 to disable

  # All thumbnails are generated into one of the sizes listed here. The first size is used as
  # the default for when no width or height is requested. The media repository will return
  # either an exact match or the next largest size of thumbnail.
  sizes:
  - width: 32
    height: 32
  - width: 96
    height: 96
  - width: 320
    height: 240
  - width: 640
    height: 480
  - width: 800
    height: 600

# Controls for the rate limit functionality
rateLimit:
  # Set this to false if rate limiting is handled at a higher level or you don't want it enabled.
  enabled: true

  # The number of requests per second before an IP will be rate limited. Must be a whole number.
  requestsPerSecond: 1

  # The number of requests an IP can send at once before the rate limit is actually considered.
  burst: 10

# Identicons are generated avatars for a given username. Some clients use these to give users a
# default avatar after signing up. Identicons are not part of the official matrix spec, therefore
# this feature is completely optional.
identicons:
  enabled: true
