# General repo configuration
repo:
  bindAddress: '127.0.0.1'
  port: 8000

  # Where to store the logs, relative to where the repo is started from. Logs will be automatically
  # rotated every day and held for 14 days.
  logDirectory: logs

# The database configuration for the media repository
database:
  # Currently only "postgres" is supported.
  postgres: "postgres://your_username:your_password@localhost/database_name?sslmode=disable"

# The configuration for the homeservers this media repository is known to control. Servers
# not listed here will not be able to upload media.
homeservers:
  - name: t2bot.io # This should match the Host header given to the media repo
    downloadRequiresAuth: false # Set to true to require auth on downloads and identicons
    csApi: "https://t2bot.io/" # The base URL to where the homeserver can actually be reached

# The file upload settings for the media repository
uploads:
  maxBytes: 104857600 # 100MB default, 0 to disable

  # This is intended for larger deployments where media should be distributed among other
  # directories, drives, servers, etc. For smaller deployments, a single entry in this list
  # is recommended.
  storagePaths:
    - /var/matrix/media

# The file download settings when retrieving media from other servers
downloads:
  maxBytes: 104857600 # 100MB default, 0 to disable

  # The number of workers to use when downloading remote media. Raise this number if remote
  # media is downloading slowly or timing out.
  #
  # Maximum memory usage = numWorkers multiplied by the maximum download size
  # Average memory usage is dependent on how many concurrent downloads your users are doing.
  numWorkers: 10

  # The cache control settings for downloads. This can help speed up downloads for users by
  # keeping popular media in the cache.
  cache:
    enabled: true

    # The maximum size of cache to have. Higher numbers are better.
    maxSizeBytes: 1048576000 # 1GB default

    # The maximum file size to cache. This should normally be the same size as your maximum
    # upload size.
    maxFileSizeBytes: 104857600 # 100MB default

    # The number of minutes to track how many downloads a file gets
    trackedMinutes: 30

    # The number of downloads a file must receive in the window above (trackedMinutes) in
    # order to be cached.
    minDownloads: 5

    # The minimum amount of time an item should remain in the cache. This prevents the cache
    # from cycling out the file if it needs more room during this time.
    minCacheTimeSeconds: 300

    # The minimum amount of time an item should remain outside the cache once it is removed.
    minEvictedTimeSeconds: 60

# URL Preview settings
urlPreviews:
  enabled: true # If enabled, the preview_url routes will be accessible
  maxPageSizeBytes: 10485760 # 10MB default, 0 to disable
  numWords: 30 # The number of words to include in a preview (maximum)

  # The number of workers to use when generating url previews. Raise this number if url
  # previews are slow or timing out.
  #
  # Maximum memory usage = numWorkers multiplied by the maximum page size
  # Average memory usage is dependent on how many concurrent urls your users are previewing.
  numWorkers: 10

  # Either allowedNetworks or disallowedNetworks must be provided. If both are provided, they
  # will be merged. URL previews will be disabled if neither is supplied. Each entry must be
  # a CIDR range.
  disallowedNetworks:
    - "127.0.0.1/8"
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
    - "100.64.0.0/10"
    - "169.254.0.0/16"
  allowedNetworks:
    - "0.0.0.0/0" # "Everything". The blacklist will help limit this.
                  # This is the default value for this field.

# The thumbnail configuration for the media repository.
thumbnails:
  # The maximum number of bytes an image can be before the thumbnailer refuses.
  maxSourceBytes: 10485760 # 10MB default, 0 to disable

  # The number of workers to use when generating thumbnails. Raise this number if thumbnails
  # are slow to generate or timing out.
  #
  # Maximum memory usage = numWorkers multiplied by the maximum image source size
  # Average memory usage is dependent on how many thumbnails are being generated by your users
  numWorkers: 100

  # All thumbnails are generated into one of the sizes listed here. The first size is used as
  # the default for when no width or height is requested. The media repository will return
  # either an exact match or the next largest size of thumbnail.
  sizes:
    - width: 32
      height: 32
    - width: 96
      height: 96
    - width: 320
      height: 240
    - width: 640
      height: 480
    - width: 800
      height: 600

  # The content types to thumbnail when requested. Types that are not supported by the media repo
  # will not be thumbnailed (adding application/json here won't work). Clients may still not request
  # thumbnails for these types - this won't make clients automatically thumbnail these file types.
  types:
    - "image/jpeg"
    - "image/jpg"
    - "image/png"
    - "image/gif"

  # Animated thumbnails can be CPU intensive to generate. To disable the generation of animated
  # thumbnails, set this to false. If disabled, regular thumbnails will be returned.
  allowAnimated: true

  # The maximum file size to thumbnail when a capable animated thumbnail is requested. If the image
  # is larger than this, the thumbnail will be generated as a static image.
  maxAnimateSizeBytes: 10485760 # 10MB default, 0 to disable

# Controls for the rate limit functionality
rateLimit:
  # Set this to false if rate limiting is handled at a higher level or you don't want it enabled.
  enabled: true

  # The number of requests per second before an IP will be rate limited. Must be a whole number.
  requestsPerSecond: 1

  # The number of requests an IP can send at once before the rate limit is actually considered.
  burst: 10

# Identicons are generated avatars for a given username. Some clients use these to give users a
# default avatar after signing up. Identicons are not part of the official matrix spec, therefore
# this feature is completely optional.
identicons:
  enabled: true
