version: 2
jobs:
  complement:
    docker:
      - image: circleci/golang:1.14
        environment:
          GO111MODULE: "on"
          COMPLEMENT_BASE_IMAGE: complement-media-repo
          COMPLEMENT_VERSION_CHECK_ITERATIONS: 400
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build complement image
          command: 'docker build -t complement-media-repo -f Complement.Dockerfile .'
      - run:
          name: run complement
          command: './ci-complement.sh'
  build:
    docker:
      - image: circleci/golang:1.14
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/turt2live/matrix-media-repo
    steps:
      - checkout
      - run:
          name: build binaries
          command: './build.sh'
      - store_artifacts:
          path: bin/media_repo
          destination: media_repo
      - store_artifacts:
          path: bin/import_synapse
          destination: import_synapse
      - store_artifacts:
          path: bin/gdpr_export
          destination: gdpr_export
      - store_artifacts:
          path: bin/gdpr_import
          destination: gdpr_import
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - complement
