version: 2
jobs:
  build:
    branches:
      only: [master, develop]
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/turt2live/matrix-media-repo
    steps:
      - checkout
      - run: go get github.com/constabulary/gb/...
      - run: gb vendor restore
      - run: gb build all
      - store_artifacts:
          path: bin/media_repo
          destination: media_repo
      - store_artifacts:
          path: bin/import_synapse
          destination: import_synapse
