name: Main
on:
  push:
jobs:
  build:
    name: 'Go Build (1.20)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - run: './build.sh' # verify the thing compiles first
  test:
    name: 'Go Test (1.20)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - run: "go install -v ./cmd/compile_assets"
        env:
          GOBIN: "$PWD/bin"
      - run: "$PWD/bin/compile_assets"
      - run: "go test -c -v ./test && ./test.test '-test.v'" # cheat and work around working directory issues
        timeout-minutes: 30
