name: Main
on:
  push:
jobs:
  build:
    name: 'Build Go 1.20'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - run: './build.sh'
